name: flutter_maker
description: Generate clean code folders and file programmatically with pure dart independent code
version: 1.0.2
homepage: https://github.com/swarajkumarsingh/flutter_maker
repository: https://github.com/swarajkumarsingh/flutter_maker

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  args: ^2.3.1
  mason_logger: ^0.2.7
  pub_updater: ^0.2.1

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  build_version: ^2.1.1
  very_good_analysis: ^3.0.1

executables:
  maker: flutter_maker